// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/Lucasma95/golang-company-api/src/api/core/entities"
	mock "github.com/stretchr/testify/mock"
)

// GetCompanyByContinent is an autogenerated mock type for the GetCompanyByContinent type
type GetCompanyByContinent struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, continent
func (_m *GetCompanyByContinent) Execute(ctx context.Context, continent string) ([]entities.Company, error) {
	ret := _m.Called(ctx, continent)

	var r0 []entities.Company
	if rf, ok := ret.Get(0).(func(context.Context, string) []entities.Company); ok {
		r0 = rf(ctx, continent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Company)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, continent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGetCompanyByContinent interface {
	mock.TestingT
	Cleanup(func())
}

// NewGetCompanyByContinent creates a new instance of GetCompanyByContinent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGetCompanyByContinent(t mockConstructorTestingTNewGetCompanyByContinent) *GetCompanyByContinent {
	mock := &GetCompanyByContinent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
